### ISSUE TITLE
Automated Testing for server 

### ISSUE THREAD

**Issue by pranavpunjabi** [rbarman/OneMomentPlease#9]
https://www.npmjs.com/package/loadtest - has own API for load testing
Grunt automated testing - Widely known and accepted in industry

Others are good too. These had the best developer reviews. Add any more that you find appropriate.
Tool to be finalized soon!

**Comment by rbarman** [comment]
Grunt is pretty popular. We should also make use of a temporary email API. (https://www.guerrillamail.com/GuerrillaMailAPI.html or https://mailinator.com/apidocs.jsp)

**Comment by rbarman** [comment]
This should steer us in the right direction : https://gist.github.com/maicki/7781943

Grunt will provide automation while Mocha and Chai are testing/assertion frameworks

**Comment by rbarman** [comment]
Now with https://github.com/rbarman/OneMomentPlease/commit/9c29fb4122a87d9b6d4b6ebb13fce57bfa7cbf3d we have testing with Mocha and Chai.  

I have created 2 sample tests for us to build off of. All tests should be put in the test/ folder. 
We can run the tests and see the output with :  `npm test.`
